[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
    'jira == 3.*',
    'python-dateutil == 2.*',
    'requests == 2.*',
    'SQLAlchemy == 2.*',
]
name = "reporting"
requires-python = ">=3.10"
version = "1.4.0"

[project.optional-dependencies]
dev = [
    "black",
    "Faker",
    "mypy",
    "pytest",
    "pytest-cov",
    "types-python-dateutil",
    "types-requests",
]

[project.scripts]
reporting = "reporting.cli:main"

[tool.pytest.ini_options]
addopts = "-ra"
minversion = "8.0"
testpaths = ["tests"]

[tool.setuptools]
include-package-data = true
