#!/bin/sh

echo "Running format and type checking"

. .venv/bin/activate
make check
RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo "Formatting or type checking failed. Commit aborted."
    exit 1
fi

echo "All checks passed. Proceeding with commit."
exit 0
